In [0]:
import numpy as np



In [0]:
a=np.array([1,2,3])

print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

b=np.array([1.0,2.2,3.5])
print(b.dtype)

[1 2 3]
(3,)
1
int64
float64


In [0]:
c=np.array([(1,2,3),(3,4,5)])
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(np.sum(c))
d=c.flatten()
print(d)
print(d.ndim)
print(c)
print(d[0])
d[0]=100
print(d)
print(c)
e=c.ravel()
print(e)
e[0]=100
print(e)
print(c)

[[1 2 3]
 [3 4 5]]
2
(2, 3)
6
18
[1 2 3 3 4 5]
1
[[1 2 3]
 [3 4 5]]
1
[100   2   3   3   4   5]
[[1 2 3]
 [3 4 5]]
[1 2 3 3 4 5]
[100   2   3   3   4   5]
[[100   2   3]
 [  3   4   5]]


In [0]:
one=np.ones((3,3))
print(one)
#help(np.ones)
zero=np.zeros((3,3))
print(zero)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
arr=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr[0:3,0:3:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
[[1 3]
 [4 6]
 [7 9]]
